### ISSUE TITLE
[Critical] Issue regarding site security

### ISSUE THREAD

**Issue by caupcakes** [espageti/espageti.github.io#1]
The issue is that I am not listed as a contributor.

- [x] I have read the docs
- [x] I have not opened an issue about the same thing before
- [x] This is a critical issue
- [x] I am not from the Microsoft service department
- [ ] I am paying taxes (trust me)

This is critical. I might have to submit a pull request soon if this is not fixed internally.

**Comment by espageti** [comment]
do it coward

**Comment by arv-k** [comment]
i will submit pull rq this is a very big issue as I too am not listed ad a contributor

**Comment by caupcakes** [comment]
This issue is still not resolved. Please lmk when it gets resolved.

**Comment by espageti** [comment]
issue is resolved the day is saved
